import { useState } from "react";
import { Button, Card, Form, Input, InputNumber, message, Modal, Select, Space, Table, Tabs, Tag, Typography, Upload } from "antd";
import { UploadOutlined } from "@ant-design/icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { UploadProps } from "antd";
import { api, json } from "./api";

type Version = { id: string; version: number; status: string };
type Courseware = { id: string; title: string; type: string; versions: Version[] };
type Template = { id: string; name: string; type: string; items: Array<{ coursewareVersion: { courseware: { title: string }; version: number } }> };
type Bank = { id: string; name: string; questions: Array<{ id: string; prompt: string; type: string }> };
type Paper = { id: string; name: string; mode: string };
type Person = { id: string; name: string; status: string };
type Project = { id: string; name: string; status: string };
type Batch = { id: string; name: string; type: string; assignments: unknown[]; project?: { name: string } | null };
const types = ["three_level", "project_induction", "routine", "change_update"].map((value) => ({ value, label: value }));
const scope = { scopeType: "company", scopeId: null };

export function CoursewarePage() {
  const qc = useQueryClient(); const coursewares = useQuery({ queryKey: ["coursewares"], queryFn: () => api<Courseware[]>("/api/coursewares") }); const templates = useQuery({ queryKey: ["training-templates"], queryFn: () => api<Template[]>("/api/training-templates") });
  const [courseOpen, setCourseOpen] = useState(false); const [templateOpen, setTemplateOpen] = useState(false); const [kind, setKind] = useState("rich_text"); const [fileId, setFileId] = useState<string>();
  const createCourse = useMutation({ mutationFn: (v: Record<string, unknown>) => api<Courseware>("/api/coursewares", json("POST", { ...scope, ...v, type: kind, fileId })), onSuccess: () => { setCourseOpen(false); void qc.invalidateQueries({ queryKey: ["coursewares"] }); }, onError: (e) => message.error(e.message) });
  const createTemplate = useMutation({ mutationFn: (v: unknown) => api("/api/training-templates", json("POST", { ...scope, ...(v as object) })), onSuccess: () => { setTemplateOpen(false); void qc.invalidateQueries({ queryKey: ["training-templates"] }); }, onError: (e) => message.error(e.message) });
  const upload: NonNullable<UploadProps["customRequest"]> = async ({ file, onSuccess, onError }) => { try { const body = new FormData(); body.append("file", file as Blob); const result = await api<{ id: string }>("/api/files?kind=courseware", { method: "POST", body }); setFileId(result.id); onSuccess?.(result); } catch (e) { onError?.(e as Error); } };
  const versionOptions = (coursewares.data ?? []).flatMap((c) => c.versions.filter((v) => v.status === "published").map((v) => ({ value: v.id, label: `${c.title} v${v.version}` })));
  return <><Space className="page-title"><Typography.Title level={3}>课件与模板</Typography.Title><Button onClick={() => setCourseOpen(true)}>新建课件</Button><Button type="primary" onClick={() => setTemplateOpen(true)}>新建模板</Button></Space><Tabs items={[
    { key: "course", label: "课件版本", children: <Table rowKey="id" dataSource={coursewares.data} columns={[{ title: "名称", dataIndex: "title" }, { title: "类型", dataIndex: "type" }, { title: "版本", render: (_, row: Courseware) => row.versions.map((v) => <Tag key={v.id} color={v.status === "published" ? "green" : "default"}>v{v.version} {v.status}<Button type="link" size="small" disabled={v.status === "published"} onClick={async () => { await api(`/api/courseware-versions/${v.id}/publish`, { method: "POST" }); void coursewares.refetch(); }}>发布</Button></Tag>) }]} /> },
    { key: "template", label: "培训模板", children: <Table rowKey="id" dataSource={templates.data} columns={[{ title: "名称", dataIndex: "name" }, { title: "培训类型", dataIndex: "type" }, { title: "课件顺序", render: (_, row: Template) => row.items.map((i) => `${i.coursewareVersion.courseware.title} v${i.coursewareVersion.version}`).join(" → ") }]} /> }
  ]} />
  <Modal title="新建课件" open={courseOpen} footer={null} onCancel={() => setCourseOpen(false)}><Form layout="vertical" onFinish={(v) => createCourse.mutate(v)}><Form.Item name="title" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="类型"><Select value={kind} onChange={setKind} options={[{ value: "rich_text", label: "图文课件" }, { value: "single_html", label: "单文件 HTML" }]} /></Form.Item>{kind === "rich_text" ? <Form.Item name="richText" label="图文内容" rules={[{ required: true }]}><Input.TextArea rows={8} /></Form.Item> : <Form.Item label="HTML 文件" required><Upload accept=".html,text/html" maxCount={1} customRequest={upload}><Button icon={<UploadOutlined />}>上传</Button></Upload></Form.Item>}<Button type="primary" htmlType="submit" loading={createCourse.isPending}>创建草稿</Button></Form></Modal>
  <Modal title="新建培训模板" open={templateOpen} footer={null} onCancel={() => setTemplateOpen(false)}><Form layout="vertical" onFinish={(v) => createTemplate.mutate(v)}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="type" label="培训类型" rules={[{ required: true }]}><Select options={types} /></Form.Item><Form.Item name="coursewareVersionIds" label="已发布课件（选择顺序即展示顺序）" rules={[{ required: true }]}><Select mode="multiple" options={versionOptions} /></Form.Item><Button type="primary" htmlType="submit">保存模板</Button></Form></Modal></>;
}

export function QuestionsPage() {
  const qc = useQueryClient(); const banks = useQuery({ queryKey: ["question-banks"], queryFn: () => api<Bank[]>("/api/question-banks") }); const papers = useQuery({ queryKey: ["exam-papers"], queryFn: () => api<Paper[]>("/api/exam-papers") }); const [bankOpen, setBankOpen] = useState(false); const [questionOpen, setQuestionOpen] = useState(false); const [paperOpen, setPaperOpen] = useState(false); const [mode, setMode] = useState("fixed");
  const allQuestions = (banks.data ?? []).flatMap((b) => b.questions.map((q) => ({ value: q.id, label: `${b.name} · ${q.prompt}` })));
  async function create(path: string, value: unknown, keys: string[]) { await api(path, json("POST", value)); keys.forEach((key) => void qc.invalidateQueries({ queryKey: [key] })); message.success("已保存"); }
  return <><Space className="page-title"><Typography.Title level={3}>题库与试卷</Typography.Title><Button onClick={() => setBankOpen(true)}>新建题库</Button><Button onClick={() => setQuestionOpen(true)}>新增题目</Button><Button type="primary" onClick={() => setPaperOpen(true)}>新建试卷</Button></Space><Tabs items={[{ key: "banks", label: "题库", children: <Table rowKey="id" dataSource={banks.data} columns={[{ title: "题库", dataIndex: "name" }, { title: "题目数", render: (_, row: Bank) => row.questions.length }, { title: "题目", render: (_, row: Bank) => row.questions.map((q) => <Tag key={q.id}>{q.type} · {q.prompt}</Tag>) }]} /> }, { key: "papers", label: "试卷", children: <Table rowKey="id" dataSource={papers.data} columns={[{ title: "名称", dataIndex: "name" }, { title: "组卷方式", dataIndex: "mode" }]} /> }]} />
  <Modal title="新建题库" open={bankOpen} footer={null} onCancel={() => setBankOpen(false)}><Form layout="vertical" onFinish={async (v) => { await create("/api/question-banks", { ...scope, ...v }, ["question-banks"]); setBankOpen(false); }}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Modal>
  <Modal title="新增题目" open={questionOpen} footer={null} onCancel={() => setQuestionOpen(false)}><Form layout="vertical" initialValues={{ type: "single_choice" }} onFinish={async (v) => { const options = String(v.options).split("\n").map((x) => x.trim()).filter(Boolean); const correct = String(v.correct).split(",").map((x) => x.trim()).filter(Boolean); await create(`/api/question-banks/${v.bankId}/questions`, { ...v, options, correct }, ["question-banks"]); setQuestionOpen(false); }}><Form.Item name="bankId" label="题库" rules={[{ required: true }]}><Select options={(banks.data ?? []).map((b) => ({ value: b.id, label: b.name }))} /></Form.Item><Form.Item name="type" label="题型"><Select options={["single_choice", "multiple_choice", "true_false"].map((value) => ({ value, label: value }))} /></Form.Item><Form.Item name="prompt" label="题干" rules={[{ required: true }]}><Input.TextArea /></Form.Item><Form.Item name="options" label="选项（每行一个）" rules={[{ required: true }]}><Input.TextArea /></Form.Item><Form.Item name="correct" label="正确答案（多个用逗号）" rules={[{ required: true }]}><Input /></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Modal>
  <Modal title="新建试卷" open={paperOpen} footer={null} onCancel={() => setPaperOpen(false)}><Form layout="vertical" onFinish={async (v) => { const body = mode === "fixed" ? { name: v.name, mode, items: (v.questionIds as string[]).map((questionId) => ({ questionId, score: 100 / v.questionIds.length })) } : { name: v.name, mode, bankId: v.bankId, randomCount: v.randomCount }; await create("/api/exam-papers", body, ["exam-papers"]); setPaperOpen(false); }}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="方式"><Select value={mode} onChange={setMode} options={[{ value: "fixed", label: "固定试卷" }, { value: "random", label: "随机组卷" }]} /></Form.Item>{mode === "fixed" ? <Form.Item name="questionIds" label="题目" rules={[{ required: true }]}><Select mode="multiple" options={allQuestions} /></Form.Item> : <><Form.Item name="bankId" label="题库" rules={[{ required: true }]}><Select options={(banks.data ?? []).map((b) => ({ value: b.id, label: b.name }))} /></Form.Item><Form.Item name="randomCount" label="题量" rules={[{ required: true }]}><InputNumber min={1} /></Form.Item></>}<Button type="primary" htmlType="submit">保存</Button></Form></Modal></>;
}

export function TrainingPage() {
  const qc = useQueryClient(); const batches = useQuery({ queryKey: ["training-batches"], queryFn: () => api<Batch[]>("/api/training-batches") }); const templates = useQuery({ queryKey: ["training-templates"], queryFn: () => api<Template[]>("/api/training-templates") }); const papers = useQuery({ queryKey: ["exam-papers"], queryFn: () => api<Paper[]>("/api/exam-papers") }); const persons = useQuery({ queryKey: ["persons"], queryFn: () => api<Person[]>("/api/persons") }); const projects = useQuery({ queryKey: ["projects"], queryFn: () => api<Project[]>("/api/projects") }); const [open, setOpen] = useState(false);
  return <><Space className="page-title"><Typography.Title level={3}>培训安排</Typography.Title><Button type="primary" onClick={() => setOpen(true)}>创建并下发</Button><Button onClick={async () => { const r = await api<{ processed: number }>("/api/training-batches/bootstrap-three-level", { method: "POST" }); message.success(`已处理 ${r.processed} 人`); void batches.refetch(); }}>为 active employee 生成三级教育</Button></Space><Card><Table rowKey="id" dataSource={batches.data} columns={[{ title: "培训", dataIndex: "name" }, { title: "类型", dataIndex: "type" }, { title: "项目", render: (_, row: Batch) => row.project?.name ?? "—" }, { title: "人数", render: (_, row: Batch) => row.assignments.length }]} /></Card>
  <Modal title="创建培训并下发" open={open} footer={null} onCancel={() => setOpen(false)}><Form layout="vertical" initialValues={{ durationMin: 30, passScore: 80, maxAttempts: 3 }} onFinish={async (v) => { await api("/api/training-batches", json("POST", v)); message.success("下发成功"); setOpen(false); void qc.invalidateQueries({ queryKey: ["training-batches"] }); }}><Form.Item name="name" label="培训名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="type" label="培训类型" rules={[{ required: true }]}><Select options={types} /></Form.Item><Form.Item name="templateId" label="模板" rules={[{ required: true }]}><Select options={(templates.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item><Form.Item name="paperId" label="试卷" rules={[{ required: true }]}><Select options={(papers.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item><Form.Item name="projectId" label="项目入场教育绑定项目"><Select allowClear options={(projects.data ?? []).filter((x) => x.status === "active").map((x) => ({ value: x.id, label: x.name }))} /></Form.Item><Form.Item name="personIds" label="选择人员" rules={[{ required: true }]}><Select mode="multiple" options={(persons.data ?? []).filter((x) => x.status === "active").map((x) => ({ value: x.id, label: x.name }))} /></Form.Item><Space><Form.Item name="durationMin" label="时长（分钟）"><InputNumber min={1} /></Form.Item><Form.Item name="passScore" label="合格分"><InputNumber min={0} max={100} /></Form.Item><Form.Item name="maxAttempts" label="最大次数"><InputNumber min={1} /></Form.Item></Space><Button type="primary" htmlType="submit">确认下发</Button></Form></Modal></>;
}
