import { useMemo, useState, type Key } from "react";
import { Button, Card, Col, DatePicker, Form, Input, InputNumber, message, Modal, Row, Select, Space, Statistic, Table, Tabs, Tag, Typography, Upload } from "antd";
import { UploadOutlined } from "@ant-design/icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, json } from "./api";

type Option = { id: string; name: string };
type Overview = { required: number; completed: number; incomplete: number; failed: number; locked: number; pendingRequests: number; people: Array<{ id: string; person: Option; batch: Option; status: string }> };
type Assignment = { id: string; status: string; displayStatus: string; person: { id: string; name: string; organizations: Option[] }; batch: { id: string; name: string; type: string; source: string; project: Option | null }; progress: { completed: number; total: number }; latestAttempt: { score: number | null; passed: boolean | null } | null; attemptCount: number; signedAt: string | null; confirmation: unknown };
type RequestRow = { id: string; type: string; status: string; applicant: string; summary: Record<string, unknown>; reviewNote: string | null; createdAt: string };
type Batch = Option & { type: string; assignments: unknown[] };
const statusNames: Record<string, string> = { not_started: "未开始", pending_learning: "待学习", learning: "学习中", pending_exam: "待考试", failed: "考试不合格", remediation_required: "需补学", locked: "已锁定", pending_signature: "待签字", confirmation_pending: "待项目确认", completed: "已完成", cancelled: "已取消" };
const typeNames: Record<string, string> = { three_level: "三级教育", project_induction: "项目入场", routine: "日常/年度", change_update: "变化补充" };
const queryString = (values: Record<string, string | undefined>) => { const params = new URLSearchParams(); Object.entries(values).forEach(([key, value]) => value && params.set(key, value)); const text = params.toString(); return text ? `?${text}` : ""; };

export function DashboardPage() {
  const [filters, setFilters] = useState<Record<string, string | undefined>>({});
  const organizations = useQuery({ queryKey: ["organizations"], queryFn: () => api<Option[]>("/api/organizations") });
  const projects = useQuery({ queryKey: ["projects"], queryFn: () => api<Option[]>("/api/projects") });
  const batches = useQuery({ queryKey: ["training-batches"], queryFn: () => api<Batch[]>("/api/training-batches") });
  const overview = useQuery({ queryKey: ["management-overview", filters], queryFn: () => api<Overview>(`/api/management/overview${queryString(filters)}`) });
  const preferences = useQuery({ queryKey: ["dashboard-preferences"], queryFn: () => api<string[]>("/api/preferences/dashboard") });
  const cards = [
    ["required", "应培训人数", overview.data?.required ?? 0], ["completed", "已完成人数", overview.data?.completed ?? 0], ["incomplete", "未完成人数", overview.data?.incomplete ?? 0],
    ["failed", "考试不合格人数", overview.data?.failed ?? 0], ["locked", "考试锁定人数", overview.data?.locked ?? 0], ["pendingRequests", "待审核申请数", overview.data?.pendingRequests ?? 0]
  ] as const;
  const visible = preferences.data ?? cards.map(([key]) => key);
  return <><Space className="page-title"><Typography.Title level={3}>管理首页</Typography.Title></Space><Card className="filters"><Space wrap>
    <Select allowClear placeholder="按组织" style={{ width: 180 }} options={(organizations.data ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(organizationId) => setFilters((v) => ({ ...v, organizationId }))} />
    <Select allowClear placeholder="按项目" style={{ width: 180 }} options={(projects.data ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(projectId) => setFilters((v) => ({ ...v, projectId }))} />
    <Select allowClear placeholder="按培训任务" style={{ width: 240 }} options={(batches.data ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(batchId) => setFilters((v) => ({ ...v, batchId }))} />
    <Select mode="multiple" value={visible} style={{ minWidth: 280 }} onChange={async (value) => { await api("/api/preferences/dashboard", json("PUT", value)); void preferences.refetch(); }} options={cards.map(([value, label]) => ({ value, label }))} placeholder="显示统计卡片" />
  </Space></Card><Row gutter={[16, 16]} className="section-card">{cards.filter(([key]) => visible.includes(key)).map(([key, title, value]) => <Col xs={24} sm={12} lg={8} key={key}><Card><Statistic title={title} value={value} /></Card></Col>)}</Row>
  <Card className="section-card" title="谁还没完成、为什么没完成"><Table rowKey="id" pagination={{ pageSize: 10 }} dataSource={overview.data?.people} columns={[{ title: "姓名", render: (_, row) => row.person.name }, { title: "培训任务", render: (_, row) => row.batch.name }, { title: "当前原因", dataIndex: "status", render: (value) => statusNames[value] ?? value }]} /></Card></>;
}

export function RecordsPage() {
  const qc = useQueryClient(); const [batchId, setBatchId] = useState<string>(); const [status, setStatus] = useState<string>(); const [selected, setSelected] = useState<Key[]>([]); const [unlock, setUnlock] = useState<Assignment>(); const [request, setRequest] = useState<RequestRow>(); const [decision, setDecision] = useState<"approve" | "reject">("approve"); const [attachmentIds, setAttachmentIds] = useState<string[]>([]);
  const assignments = useQuery({ queryKey: ["management-assignments", batchId, status], queryFn: () => api<Assignment[]>(`/api/management/assignments${queryString({ batchId, status })}`) });
  const batches = useQuery({ queryKey: ["training-batches"], queryFn: () => api<Batch[]>("/api/training-batches") }); const persons = useQuery({ queryKey: ["persons"], queryFn: () => api<Option[]>("/api/persons") }); const projects = useQuery({ queryKey: ["projects"], queryFn: () => api<Option[]>("/api/projects") }); const organizations = useQuery({ queryKey: ["organizations"], queryFn: () => api<Option[]>("/api/organizations") }); const papers = useQuery({ queryKey: ["exam-papers"], queryFn: () => api<Option[]>("/api/exam-papers") });
  const requests = useQuery({ queryKey: ["management-requests"], queryFn: () => api<RequestRow[]>("/api/management/requests") });
  const refresh = () => { setSelected([]); void assignments.refetch(); void qc.invalidateQueries({ queryKey: ["management-overview"] }); };
  const remind = async () => { if (!selected.length) return message.warning("请选择人员"); const result = await api<{ created: number }>("/api/management/reminders", json("POST", { assignmentIds: selected })); message.success(`已生成 ${result.created} 条系统提醒`); refresh(); };
  const confirm = async () => { if (!selected.length) return message.warning("请选择待项目确认人员"); const result = await api<{ confirmed: number }>("/api/management/confirmations", json("POST", { assignmentIds: selected })); message.success(`已确认 ${result.confirmed} 人`); refresh(); };
  const reconfirm = async () => { const rows = (assignments.data ?? []).filter((row) => selected.includes(row.id)); const projectId = rows[0]?.batch.project?.id; if (!projectId || rows.some((row) => row.batch.project?.id !== projectId)) return message.warning("请选择同一项目的人员"); await api(`/api/management/projects/${projectId}/reconfirmation`, json("POST", { personIds: rows.map((row) => row.person.id) })); message.success("已建立重新现场确认批次"); refresh(); void batches.refetch(); };
  const columns = [
    { title: "姓名", render: (_: unknown, row: Assignment) => row.person.name }, { title: "所属组织", render: (_: unknown, row: Assignment) => row.person.organizations.map((x) => x.name).join("、") }, { title: "项目", render: (_: unknown, row: Assignment) => row.batch.project?.name ?? "—" },
    { title: "培训任务", render: (_: unknown, row: Assignment) => row.batch.name }, { title: "课件进度", render: (_: unknown, row: Assignment) => `${row.progress.completed}/${row.progress.total}` }, { title: "分数", render: (_: unknown, row: Assignment) => row.latestAttempt?.score ?? "—" }, { title: "考试次数", dataIndex: "attemptCount" },
    { title: "签字", render: (_: unknown, row: Assignment) => row.signedAt ? "已签" : "未签" }, { title: "状态", render: (_: unknown, row: Assignment) => <Tag color={row.status === "completed" ? "green" : row.status === "locked" ? "red" : "orange"}>{statusNames[row.displayStatus] ?? row.displayStatus}</Tag> },
    { title: "操作", render: (_: unknown, row: Assignment) => row.status === "locked" ? <Button size="small" onClick={() => setUnlock(row)}>解锁</Button> : null }
  ];
  const offline = async (values: Record<string, unknown>) => { const date = values.date as { toISOString(): string }; await api("/api/management/offline-batches", json("POST", { ...values, date: date.toISOString(), attachmentIds })); message.success("线下培训已逐人建档"); setAttachmentIds([]); void batches.refetch(); };
  return <><Typography.Title level={3}>进度与记录</Typography.Title><Tabs items={[
    { key: "progress", label: "人员培训状态", children: <><Card className="filters"><Space wrap><Select allowClear placeholder="选择培训任务" style={{ width: 260 }} value={batchId} onChange={setBatchId} options={(batches.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /><Select allowClear placeholder="状态" style={{ width: 160 }} value={status} onChange={setStatus} options={["not_started", "learning", "pending_exam", "failed", "locked", "pending_signature", "completed"].map((value) => ({ value, label: statusNames[value] }))} /><Button type="primary" onClick={() => void remind()}>批量催办</Button><Button onClick={() => void confirm()}>到场/交底确认</Button><Button onClick={() => void reconfirm()}>发起重新现场确认</Button></Space></Card><Table rowKey="id" rowSelection={{ selectedRowKeys: selected, onChange: setSelected }} dataSource={assignments.data} columns={columns} /></> },
    { key: "requests", label: `审核申请${requests.data?.filter((x) => x.status === "pending").length ? ` (${requests.data.filter((x) => x.status === "pending").length})` : ""}`, children: <Table rowKey="id" dataSource={requests.data} columns={[{ title: "申请人", dataIndex: "applicant" }, { title: "类型", dataIndex: "type" }, { title: "申请摘要", render: (_, row: RequestRow) => Object.values(row.summary).filter(Boolean).join("；") }, { title: "状态", dataIndex: "status" }, { title: "审核意见", dataIndex: "reviewNote" }, { title: "操作", render: (_, row: RequestRow) => row.status === "pending" ? <Space><Button type="primary" size="small" onClick={() => { setDecision("approve"); setRequest(row); }}>通过</Button><Button danger size="small" onClick={() => { setDecision("reject"); setRequest(row); }}>驳回</Button></Space> : null }]} /> },
    { key: "offline", label: "线下培训录入", children: <Card><Form layout="vertical" onFinish={(v) => void offline(v)}><Row gutter={16}><Col span={12}><Form.Item name="name" label="培训名称" rules={[{ required: true }]}><Input /></Form.Item></Col><Col span={12}><Form.Item name="type" label="培训类型" rules={[{ required: true }]}><Select options={Object.entries(typeNames).map(([value, label]) => ({ value, label }))} /></Form.Item></Col></Row><Form.Item name="content" label="培训内容" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item><Row gutter={16}><Col span={6}><Form.Item name="date" label="培训日期" rules={[{ required: true }]}><DatePicker style={{ width: "100%" }} /></Form.Item></Col><Col span={6}><Form.Item name="startTime" label="开始时间"><Input placeholder="08:30" /></Form.Item></Col><Col span={6}><Form.Item name="endTime" label="结束时间"><Input placeholder="10:30" /></Form.Item></Col><Col span={6}><Form.Item name="hours" label="实际学时" rules={[{ required: true }]}><InputNumber min={0.5} max={24} style={{ width: "100%" }} /></Form.Item></Col></Row><Form.Item name="instructor" label="授课人" rules={[{ required: true }]}><Input /></Form.Item><Row gutter={16}><Col span={12}><Form.Item name="organizationId" label="组织"><Select allowClear options={(organizations.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item></Col><Col span={12}><Form.Item name="projectId" label="项目"><Select allowClear options={(projects.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item></Col></Row><Form.Item name="personIds" label="参加人员（逐人建档）" rules={[{ required: true }]}><Select mode="multiple" options={(persons.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item><Form.Item name="paperId" label="需要线上考试时选择试卷"><Select allowClear options={(papers.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item><Form.Item name="note" label="备注"><Input.TextArea /></Form.Item><Form.Item label="附件"><Upload customRequest={async ({ file, onSuccess, onError }) => { try { const body = new FormData(); body.append("file", file as Blob); const result = await api<{ id: string }>("/api/files?kind=attachment", { method: "POST", body }); setAttachmentIds((current) => [...current, result.id]); onSuccess?.(result); } catch (error) { onError?.(error as Error); } }}><Button icon={<UploadOutlined />}>上传附件</Button></Upload></Form.Item><Button type="primary" htmlType="submit">保存线下培训</Button></Form></Card> }
  ]} />
  <Modal title={`${unlock?.person.name ?? ""} · 考试解锁`} open={!!unlock} footer={null} onCancel={() => setUnlock(undefined)}><Typography.Paragraph>当前培训：{unlock?.batch.name}；历史考试 {unlock?.attemptCount} 次。解锁不会修改旧成绩。</Typography.Paragraph><Form layout="vertical" onFinish={async ({ reason }) => { await api(`/api/management/assignments/${unlock!.id}/unlock`, json("POST", { reason })); message.success("已解锁，需先完成补学"); setUnlock(undefined); refresh(); }}><Form.Item name="reason" label="解锁原因" rules={[{ required: true, min: 2 }]}><Input.TextArea /></Form.Item><Button type="primary" htmlType="submit">确认解锁</Button></Form></Modal>
  <Modal title={decision === "approve" ? "审核通过" : "驳回申请"} open={!!request} footer={null} onCancel={() => setRequest(undefined)}><Form layout="vertical" onFinish={async (values) => { const special = ["binding", "registration"].includes(request!.type); const path = decision === "reject" ? `/api/management/requests/${request!.id}/reject` : special ? `/api/binding-requests/${request!.id}/approve` : `/api/management/requests/${request!.id}/approve`; await api(path, json("POST", values)); message.success("审核已完成"); setRequest(undefined); void requests.refetch(); }}><Typography.Paragraph>{request?.applicant} · {request?.type}</Typography.Paragraph>{decision === "approve" && request?.type === "binding" && <Form.Item name="personId" label="绑定人员档案" rules={[{ required: true }]}><Select options={(persons.data ?? []).map((x) => ({ value: x.id, label: x.name }))} /></Form.Item>}<Form.Item name="note" label="审核意见" rules={decision === "reject" ? [{ required: true, min: 2 }] : []}><Input.TextArea /></Form.Item><Button danger={decision === "reject"} type="primary" htmlType="submit">确认{decision === "approve" ? "通过" : "驳回"}</Button></Form></Modal></>;
}

const reports = [{ value: "ledger", label: "三级安全教育台账" }, { value: "cards", label: "三级安全教育记录卡" }, { value: "attendance", label: "培训签到表" }, { value: "scores", label: "考试成绩单" }, { value: "annual", label: "年度培训统计" }];
export function ReportsPage() {
  const [type, setType] = useState("ledger"); const [year, setYear] = useState(new Date().getFullYear());
  const report = useQuery({ queryKey: ["report", type, year], queryFn: () => api<{ title: string; rows: Record<string, unknown>[] }>(`/api/reports/${type}?year=${year}`) });
  const columns = useMemo(() => Object.keys(report.data?.rows[0] ?? {}).filter((key) => key !== "签字文件ID").map((key) => ({ title: key, dataIndex: key, render: (value: unknown, row: Record<string, unknown>) => key === "本人签字" && row.签字文件ID ? <img className="signature-preview" src={`/api/files/${row.签字文件ID}`} /> : String(value ?? "") })), [report.data]);
  return <><Space className="page-title"><Typography.Title level={3}>报表与设置</Typography.Title></Space><Card className="filters"><Space wrap><Select value={type} onChange={setType} style={{ width: 220 }} options={reports} /><InputNumber min={2020} max={2100} value={year} onChange={(value) => setYear(value ?? new Date().getFullYear())} addonAfter="年度" /><Button onClick={() => window.print()}>打印 / 保存 PDF</Button><Button href={`/api/reports/${type}?year=${year}&format=csv`}>导出 CSV</Button></Space></Card><Card className="print-report section-card" title={report.data?.title}><Table rowKey={(_, index) => String(index)} pagination={false} scroll={{ x: true }} dataSource={report.data?.rows} columns={columns} /></Card></>;
}
