const api = require('../../utils/api')
const typeNames = { employee: '正式员工', contractor: '外协人员', temporary_individual: '临时个人' }
const roleNames = { company_admin: '公司管理员', org_leader: '组织负责人', org_admin: '组织管理员', field_reporter: '野外项目报送人员', project_admin: '项目管理员' }
Page({
  data: { canManage: false, person: null, security: null, certificates: [], photoPath: '', organizations: [], targetIndex: -1, transferReason: '', transferring: false, exporting: false, phoneChanging: false, newPhone: '', phoneCode: '' },
  async onShow() { await this.load() },
  async load() { try { const [me, person, organizations, certificates, security] = await Promise.all([api.request('/api/auth/me'), api.request('/api/me/profile'), api.request('/api/me/organization-options'), api.request('/api/me/certificates'), api.request('/api/auth/security')]); this.setData({ canManage: me.roles.some((role) => ['company_admin', 'org_leader', 'org_admin', 'project_admin'].includes(role.role)), person: { ...person, typeText: typeNames[person.type] || person.type, organizationText: person.organizations.map((item) => item.name).join('、') || '待补录' }, security: { ...security, methodText: [security.loginMethods.password && '密码', security.loginMethods.phone && '手机号', security.loginMethods.wechat && '微信'].filter(Boolean).join('、') || '待激活', roles: security.roles.map((role) => ({ ...role, text: `${roleNames[role.role] || role.role}${role.scopeName ? ` · ${role.scopeName}` : ''}` })) }, organizations, certificates: certificates.map((item) => ({ ...item, expiresText: item.expiresAt ? item.expiresAt.slice(0, 10) : '长期有效', expired: item.expiresAt && new Date(item.expiresAt).getTime() < Date.now() })) }); if (person.photoFileId) this.setData({ photoPath: await api.download(`/api/files/${person.photoFileId}`) }); } catch (error) { wx.showToast({ title: error.message || '个人信息加载失败', icon: 'none' }); } },
  async choosePhoto() { try { const result = await new Promise((resolve, reject) => wx.chooseMedia({ count: 1, mediaType: ['image'], sourceType: ['album', 'camera'], success: resolve, fail: reject })); const file = await api.uploadPhoto(result.tempFiles[0].tempFilePath); await api.request('/api/me/profile/photo', 'PATCH', { photoFileId: file.id }); wx.showToast({ title: '照片已更新' }); await this.load(); } catch (error) { if (error.errMsg && error.errMsg.includes('cancel')) return; wx.showToast({ title: error.message || '照片更新失败', icon: 'none' }); } },
  async revealNationalId() { try { const login = await new Promise((resolve, reject) => wx.login({ success: resolve, fail: reject })); const access = await api.request('/api/wechat/reauthenticate', 'POST', { code: login.code }); const sensitive = await api.request('/api/me/profile/sensitive', 'GET', undefined, { 'x-sensitive-token': access.token }); this.setData({ 'person.nationalId': sensitive.nationalId }); if (this.nationalIdTimer) clearTimeout(this.nationalIdTimer); this.nationalIdTimer = setTimeout(() => this.setData({ 'person.nationalId': null }), 5 * 60 * 1000); } catch (error) { wx.showToast({ title: error.message || '身份验证失败', icon: 'none' }); } },
  onHide() { if (this.nationalIdTimer) clearTimeout(this.nationalIdTimer); this.setData({ 'person.nationalId': null }) },
  chooseDepartment(e) { this.setData({ targetIndex: Number(e.detail.value) }) }, setTransferReason(e) { this.setData({ transferReason: e.detail.value }) },
  async requestTransfer() { const target = this.data.organizations[this.data.targetIndex]; if (!target || this.data.transferReason.trim().length < 2) return wx.showToast({ title: '请选择部门并填写原因', icon: 'none' }); this.setData({ transferring: true }); try { await api.request('/api/me/department-transfer-requests', 'POST', { organizationId: target.id, reason: this.data.transferReason }); wx.showToast({ title: '申请已提交' }); this.setData({ targetIndex: -1, transferReason: '' }); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } finally { this.setData({ transferring: false }); } },
  async subscribe() { try { const config = await api.request('/api/wechat/subscription-config'); if (!config.templateIds.length) return wx.showToast({ title: '订阅消息尚未配置', icon: 'none' }); const statuses = await new Promise((resolve, reject) => wx.requestSubscribeMessage({ tmplIds: config.templateIds, success: resolve, fail: reject })); await api.request('/api/wechat/subscription-consent', 'POST', { statuses }); wx.showToast({ title: '提醒设置已保存' }); } catch (error) { wx.showToast({ title: error.message || '未完成授权', icon: 'none' }); } },
  async exportMyArchive() { if (!this.data.person || this.data.exporting) return; const modal = await wx.showModal({ title: '生成本人资料文件', content: '文件含完整身份信息和私有附件，仅保留十分钟且只能下载一次。', confirmText: '确认生成' }); if (!modal.confirm) return; this.setData({ exporting: true }); try { const created = await api.request('/api/sensitive-exports', 'POST', { scopeType: 'self', scopeId: this.data.person.id, categories: ['photos', 'signatures', 'certificates', 'training_attachments'], confirmed: true }); let job; for (let index = 0; index < 15; index += 1) { const rows = await api.request('/api/sensitive-exports'); job = rows.find((item) => item.id === created.id); if (job?.status === 'ready' || job?.status === 'failed') break; await new Promise((resolve) => setTimeout(resolve, 1000)); } if (!job || job.status !== 'ready') throw new Error(job?.error || '资料仍在生成，请稍后重试'); const grant = await api.request(`/api/sensitive-exports/${job.id}/token`, 'POST'); const path = await api.downloadPost(`/api/sensitive-exports/${job.id}/download`, { token: grant.token }); if (wx.shareFileMessage) wx.shareFileMessage({ filePath: path, fileName: '我的安全生产资料.zip' }); else wx.showModal({ title: '文件已保存', content: path, showCancel: false }); } catch (error) { wx.showToast({ title: error.message || '资料生成失败', icon: 'none' }); } finally { this.setData({ exporting: false }); } },
  setNewPhone(e) { this.setData({ newPhone: e.detail.value }) }, setPhoneCode(e) { this.setData({ phoneCode: e.detail.value }) },
  async sendPhoneCode() { if (!/^1\d{10}$/.test(this.data.newPhone)) return wx.showToast({ title: '请输入正确手机号', icon: 'none' }); try { await api.request('/api/me/phone/code', 'POST', { phone: this.data.newPhone }); wx.showToast({ title: '验证码已发送' }); } catch (error) { wx.showToast({ title: error.message || '发送失败', icon: 'none' }); } },
  async confirmPhone() { if (!/^\d{6}$/.test(this.data.phoneCode)) return wx.showToast({ title: '请输入六位验证码', icon: 'none' }); this.setData({ phoneChanging: true }); try { await api.request('/api/me/phone/confirm', 'POST', { phone: this.data.newPhone, code: this.data.phoneCode }); wx.showModal({ title: '手机号已更新', content: '为保护账号安全，请使用新手机号重新登录。', showCancel: false, success: () => { api.clearSession(); wx.reLaunch({ url: '/pages/login/index' }); } }); } catch (error) { wx.showToast({ title: error.message || '修改失败', icon: 'none' }); } finally { this.setData({ phoneChanging: false }); } },
  changeRequest() { wx.navigateTo({ url: '/pages/change-request/index' }) }, manage() { wx.navigateTo({ url: '/pages/management/index' }) }, async logout() { const { confirm } = await wx.showModal({ title: '退出登录', content: '只退出当前设备，其他设备保持登录。', confirmText: '退出' }); if (!confirm) return; await api.logout(); getApp().globalData.session = null; wx.reLaunch({ url: '/pages/login/index' }); }, async logoutAll() { const { confirm } = await wx.showModal({ title: '退出全部设备', content: '该账号在所有设备上的登录都将失效。', confirmText: '全部退出' }); if (!confirm) return; await api.logoutAll(); getApp().globalData.session = null; wx.reLaunch({ url: '/pages/login/index' }); }
})
