const api = require('../../utils/api')
const typeNames = { employee: '正式员工', contractor: '外协人员', temporary_individual: '临时个人' }
const roleNames = { company_admin: '公司管理员', org_leader: '组织负责人', org_admin: '组织管理员', field_reporter: '野外项目报送人员', project_admin: '项目管理员' }
Page({
  data: { canManage: false, person: null, security: null, certificates: [], photoPath: '', organizations: [], targetIndex: -1, transferReason: '', transferring: false },
  async onShow() { await this.load() },
  async load() { try { const [me, person, organizations, certificates, security] = await Promise.all([api.request('/api/auth/me'), api.request('/api/me/profile'), api.request('/api/me/organization-options'), api.request('/api/me/certificates'), api.request('/api/auth/security')]); this.setData({ canManage: me.roles.some((role) => ['company_admin', 'org_leader', 'org_admin', 'project_admin'].includes(role.role)), person: { ...person, typeText: typeNames[person.type] || person.type, organizationText: person.organizations.map((item) => item.name).join('、') || '待补录' }, security: { ...security, methodText: [security.loginMethods.password && '密码', security.loginMethods.phone && '手机号', security.loginMethods.wechat && '微信'].filter(Boolean).join('、') || '待激活', roles: security.roles.map((role) => ({ ...role, text: `${roleNames[role.role] || role.role}${role.scopeName ? ` · ${role.scopeName}` : ''}` })) }, organizations, certificates: certificates.map((item) => ({ ...item, expiresText: item.expiresAt ? item.expiresAt.slice(0, 10) : '长期有效', expired: item.expiresAt && new Date(item.expiresAt).getTime() < Date.now() })) }); if (person.photoFileId) this.setData({ photoPath: await api.download(`/api/files/${person.photoFileId}`) }); } catch (error) { wx.showToast({ title: error.message || '个人信息加载失败', icon: 'none' }); } },
  async choosePhoto() { try { const result = await new Promise((resolve, reject) => wx.chooseMedia({ count: 1, mediaType: ['image'], sourceType: ['album', 'camera'], success: resolve, fail: reject })); const file = await api.uploadPhoto(result.tempFiles[0].tempFilePath); await api.request('/api/me/profile/photo', 'PATCH', { photoFileId: file.id }); wx.showToast({ title: '照片已更新' }); await this.load(); } catch (error) { if (error.errMsg && error.errMsg.includes('cancel')) return; wx.showToast({ title: error.message || '照片更新失败', icon: 'none' }); } },
  chooseDepartment(e) { this.setData({ targetIndex: Number(e.detail.value) }) }, setTransferReason(e) { this.setData({ transferReason: e.detail.value }) },
  async requestTransfer() { const target = this.data.organizations[this.data.targetIndex]; if (!target || this.data.transferReason.trim().length < 2) return wx.showToast({ title: '请选择部门并填写原因', icon: 'none' }); this.setData({ transferring: true }); try { await api.request('/api/me/department-transfer-requests', 'POST', { organizationId: target.id, reason: this.data.transferReason }); wx.showToast({ title: '申请已提交' }); this.setData({ targetIndex: -1, transferReason: '' }); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } finally { this.setData({ transferring: false }); } },
  async subscribe() { try { const config = await api.request('/api/wechat/subscription-config'); if (!config.templateIds.length) return wx.showToast({ title: '订阅消息尚未配置', icon: 'none' }); const statuses = await new Promise((resolve, reject) => wx.requestSubscribeMessage({ tmplIds: config.templateIds, success: resolve, fail: reject })); await api.request('/api/wechat/subscription-consent', 'POST', { statuses }); wx.showToast({ title: '提醒设置已保存' }); } catch (error) { wx.showToast({ title: error.message || '未完成授权', icon: 'none' }); } },
  changeRequest() { wx.navigateTo({ url: '/pages/change-request/index' }) }, manage() { wx.navigateTo({ url: '/pages/management/index' }) }, async logout() { const { confirm } = await wx.showModal({ title: '退出登录', content: '只退出当前设备，其他设备保持登录。', confirmText: '退出' }); if (!confirm) return; await api.logout(); getApp().globalData.session = null; wx.reLaunch({ url: '/pages/login/index' }); }, async logoutAll() { const { confirm } = await wx.showModal({ title: '退出全部设备', content: '该账号在所有设备上的登录都将失效。', confirmText: '全部退出' }); if (!confirm) return; await api.logoutAll(); getApp().globalData.session = null; wx.reLaunch({ url: '/pages/login/index' }); }
})
