const api = require('../../utils/api')
const types = { profile_change: '姓名修改', binding_change: '微信换绑（旧申请）', department_transfer: '调换部门', identity_correction: '身份更正', contractor_unit_change: '外协单位变更', responsible_entity_change: '责任实体变更' }
const statuses = { pending: '待审核', approved: '已通过', rejected: '已驳回', withdrawn: '已撤回', cancelled: '已取消', failed: '处理失败' }
const personTypes = [{ value: 'employee', label: '正式员工' }, { value: 'contractor', label: '外协人员' }, { value: 'temporary_individual', label: '临时个人' }]
Page({
  data: { type: 'profile_change', requests: [], busy: false, personTypes, personTypeIndex: 0, businessEntities: [], contractors: [], organizationIndex: 0, contractorIndex: 0, attachmentIds: [] },
  onShow() { this.load() },
  chooseType(e) { this.setData({ type: e.detail.value }) },
  choosePersonType(e) { this.setData({ personTypeIndex: Number(e.detail.value) }) },
  chooseOrganization(e) { this.setData({ organizationIndex: Number(e.detail.value) }) },
  chooseContractor(e) { this.setData({ contractorIndex: Number(e.detail.value) }) },
  async chooseAttachment() { try { const selected = await wx.chooseMessageFile({ count: 3, type: 'file' }); const uploaded = []; for (const file of selected.tempFiles) uploaded.push(await api.uploadAttachment(file.path)); this.setData({ attachmentIds: [...this.data.attachmentIds, ...uploaded.map((file) => file.id)].slice(0, 10) }); } catch (error) { if (error?.errMsg && error.errMsg.includes('cancel')) return; wx.showToast({ title: error.message || '附件上传失败', icon: 'none' }); } },
  async load() { try { const [requests, organizations] = await Promise.all([api.request('/api/me/change-requests'), api.request('/api/me/organization-options')]); this.setData({ requests: requests.map((row) => ({ ...row, typeText: types[row.type] || row.type, statusText: statuses[row.status] || row.status, canWithdraw: (row.availableActions || []).includes('withdraw') })), businessEntities: organizations.filter((row) => row.type === 'business_entity'), contractors: organizations.filter((row) => row.type === 'contractor') }); } catch (_) {} },
  async submit(e) { this.setData({ busy: true }); try { const values = e.detail.value; const body = { type: this.data.type, name: values.name || undefined, reason: values.reason }; if (this.data.type === 'identity_correction') { body.newPersonType = personTypes[this.data.personTypeIndex].value; if (body.newPersonType !== 'employee') body.organizationId = this.data.businessEntities[this.data.organizationIndex]?.id; if (body.newPersonType === 'contractor') body.contractorOrganizationId = this.data.contractors[this.data.contractorIndex]?.id; } if (this.data.type === 'contractor_unit_change') body.organizationId = this.data.contractors[this.data.contractorIndex]?.id; if (this.data.type === 'responsible_entity_change') body.organizationId = this.data.businessEntities[this.data.organizationIndex]?.id; if (['identity_correction', 'contractor_unit_change', 'responsible_entity_change'].includes(this.data.type)) body.attachmentIds = this.data.attachmentIds; await api.request('/api/me/change-requests', 'POST', body); this.setData({ attachmentIds: [] }); wx.showToast({ title: '已提交审核' }); await this.load(); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } finally { this.setData({ busy: false }); } },
  async withdraw(e) { const result = await wx.showModal({ title: '撤回申请', editable: true, placeholderText: '请输入撤回原因' }); if (!result.confirm) return; const reason = String(result.content || '').trim(); if (reason.length < 2) return wx.showToast({ title: '请输入至少2个字', icon: 'none' }); try { await api.request(`/api/me/change-requests/${e.currentTarget.dataset.id}/withdraw`, 'POST', { reason }); wx.showToast({ title: '已撤回' }); await this.load(); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } }
})
