const api = require('../../utils/api')
const statusNames = { pending_learning: '待学习', learning: '学习中', pending_exam: '待考试', remediation_required: '需补学', locked: '已锁定', pending_signature: '待签字', confirmation_pending: '待项目确认', completed: '已完成' }
Page({
  data: { assignments: [], requests: [], persons: [], unlockReason: '', reviewNote: '', error: '' },
  async onShow() { try { const [assignments, requests, persons] = await Promise.all([api.request('/api/management/assignments'), api.request('/api/management/requests'), api.request('/api/persons')]); this.setData({ assignments: assignments.filter((row) => row.status !== 'completed').map((row) => ({ ...row, statusText: statusNames[row.status] || row.status })), requests: requests.filter((row) => row.status === 'pending'), persons, error: '' }); } catch (error) { if (error.statusCode === 403) wx.navigateBack(); else this.setData({ error: error.message }); } },
  reason(e) { this.setData({ unlockReason: e.detail.value }) }, note(e) { this.setData({ reviewNote: e.detail.value }) },
  choosePerson(e) { const index = Number(e.currentTarget.dataset.index); this.setData({ [`requests[${index}].personId`]: this.data.persons[Number(e.detail.value)].id, [`requests[${index}].personName`]: this.data.persons[Number(e.detail.value)].name }) },
  async remind(e) { await this.run(() => api.request('/api/management/reminders', 'POST', { assignmentIds: [e.currentTarget.dataset.id] }), '已催办') },
  async unlock(e) { if (this.data.unlockReason.trim().length < 2) return wx.showToast({ title: '请先填写解锁原因', icon: 'none' }); await this.run(() => api.request(`/api/management/assignments/${e.currentTarget.dataset.id}/unlock`, 'POST', { reason: this.data.unlockReason }), '已解锁，需补学') },
  async confirm(e) { await this.run(() => api.request('/api/management/confirmations', 'POST', { assignmentIds: [e.currentTarget.dataset.id] }), '已确认') },
  async review(e) { const row = this.data.requests[Number(e.currentTarget.dataset.index)]; const decision = e.currentTarget.dataset.decision; if (decision === 'reject' && this.data.reviewNote.trim().length < 2) return wx.showToast({ title: '请填写驳回意见', icon: 'none' }); if (decision === 'approve' && row.type === 'binding' && !row.personId) return wx.showToast({ title: '请选择人员档案', icon: 'none' }); const special = ['binding', 'registration'].includes(row.type); const path = decision === 'reject' ? `/api/management/requests/${row.id}/reject` : special ? `/api/binding-requests/${row.id}/approve` : `/api/management/requests/${row.id}/approve`; await this.run(() => api.request(path, 'POST', { note: this.data.reviewNote, personId: row.personId }), '审核完成') },
  async run(action, title) { try { await action(); wx.showToast({ title }); await this.onShow(); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } }
})
