import assert from "node:assert/strict";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import argon2 from "argon2";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient(); const base = process.env.SMOKE_BASE_URL ?? "http://127.0.0.1:3000";
async function call(path: string, init: RequestInit = {}, expected = 200) { if (init.method && init.method !== "GET" && init.body === undefined) init.body = "{}"; const response = await fetch(`${base}${path}`, { ...init, signal: AbortSignal.timeout(10_000) }); const body = await response.json() as any; assert.equal(response.status, expected, `${path}: ${body.error?.code} ${body.error?.message}`); return body.data as any; }
const auth = (cookie: string) => ({ cookie, "content-type": "application/json" });
async function login(username: string, password: string) { const response = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }), signal: AbortSignal.timeout(10_000) }); assert.equal(response.status, 200); const cookie = response.headers.get("set-cookie")?.split(";", 1)[0]; assert.ok(cookie); return cookie; }

async function main() {
  console.log("DAY4_SMOKE_START");
  const password = randomBytes(24).toString("base64url"); const hash = await argon2.hash(password);
  const [company, orgAdmin, projectAdmin] = await Promise.all(["company", "org", "project"].map((name) => prisma.account.create({ data: { username: `${name}-${randomUUID()}`, passwordHash: hash } })));
  const [org1, org2] = await Promise.all([1, 2].map((n) => prisma.organization.create({ data: { name: `Day4 org ${n}`, type: "department" } })));
  const [project1, project2] = await Promise.all([1, 2].map((n) => prisma.project.create({ data: { name: `Day4 project ${n}`, code: `D4-${randomUUID()}`, responsibleOrganizationId: n === 1 ? org1.id : org2.id } })));
  await prisma.roleAssignment.createMany({ data: [{ accountId: company.id, role: "company_admin", scopeType: "company" }, { accountId: orgAdmin.id, role: "org_admin", scopeType: "organization", scopeId: org1.id }, { accountId: projectAdmin.id, role: "project_admin", scopeType: "project", scopeId: project1.id }] });
  const photo = await prisma.privateFile.create({ data: { kind: "photo", storageKey: `smoke/${randomUUID()}`, originalName: "fixture.png", mimeType: "image/png", size: 1, sha256: "0".repeat(64), uploadedBy: company.id } });
  const people = await Promise.all([1, 2].map((n) => prisma.person.create({ data: { name: `Day4 learner ${n}`, phone: `1980000000${n}`, type: "employee", status: "active", nationalIdCipher: "fixture", nationalIdIv: "fixture", nationalIdTag: "fixture", nationalIdHash: createHash("sha256").update(`day4-${n}`).digest("hex"), nationalIdLast4: `100${n}`, photoFileId: photo.id, organizations: { create: { organizationId: n === 1 ? org1.id : org2.id, primary: true } }, projectMemberships: { create: { projectId: n === 1 ? project1.id : project2.id, status: "active" } } } })));
  const learner = await prisma.account.create({ data: { personId: people[0]!.id, roles: { create: { role: "learner", scopeType: "person", scopeId: people[0]!.id } }, wechatBindings: { create: { appId: "development", openid: "dev-day4-smoke", boundAt: new Date() } } } });
  const bank = await prisma.questionBank.create({ data: { name: "Day4 bank", scopeType: "company" } }); const question = await prisma.question.create({ data: { bankId: bank.id, type: "true_false", prompt: "Day4 question", options: ["正确", "错误"], correct: ["正确"] } }); const paper = await prisma.examPaper.create({ data: { name: "Day4 paper", mode: "fixed", items: { create: { questionId: question.id, sortOrder: 0, score: 100 } } } });
  const batch1 = await prisma.trainingBatch.create({ data: { businessKey: `d4:${randomUUID()}`, name: "Day4 project training", type: "project_induction", projectId: project1.id, paperId: paper.id, maxAttempts: 1 } }); const confirmBatch = await prisma.trainingBatch.create({ data: { businessKey: `d4:${randomUUID()}`, name: "Day4 confirmation", type: "project_induction", projectId: project1.id, paperId: paper.id } }); const batch2 = await prisma.trainingBatch.create({ data: { businessKey: `d4:${randomUUID()}`, name: "Day4 other training", type: "project_induction", projectId: project2.id, paperId: paper.id } });
  const locked = await prisma.trainingAssignment.create({ data: { batchId: batch1.id, personId: people[0]!.id, status: "locked", attempts: { create: { attemptNumber: 1, status: "submitted", snapshot: { questions: [] }, expiresAt: new Date(), submittedAt: new Date(), score: 20, passed: false } } } });
  const pendingConfirm = await prisma.trainingAssignment.create({ data: { batchId: confirmBatch.id, personId: people[0]!.id, status: "confirmation_pending" } });
  const outside = await prisma.trainingAssignment.create({ data: { batchId: batch2.id, personId: people[1]!.id, status: "locked" } });
  const [companyCookie, orgCookie, projectCookie] = await Promise.all([login(company.username!, password), login(orgAdmin.username!, password), login(projectAdmin.username!, password)]);
  console.log("DAY4_SMOKE_AUTH");
  await call(`/api/projects/${project1.id}/status`, { method: "PATCH", headers: auth(projectCookie), body: JSON.stringify({ status: "paused" }) }); await call(`/api/projects/${project1.id}/status`, { method: "PATCH", headers: auth(projectCookie), body: JSON.stringify({ status: "active" }) });
  assert.equal((await call("/api/management/assignments", { headers: auth(projectCookie) })).length, 2);
  await call(`/api/management/assignments/${outside.id}/unlock`, { method: "POST", headers: auth(projectCookie), body: JSON.stringify({ reason: "越权尝试" }) }, 403);
  const before = await prisma.examAttempt.findFirstOrThrow({ where: { assignmentId: locked.id } }); await call(`/api/management/assignments/${locked.id}/unlock`, { method: "POST", headers: auth(projectCookie), body: JSON.stringify({ reason: "现场确认后允许补学重考" }) }); const after = await prisma.examAttempt.findUniqueOrThrow({ where: { id: before.id } }); assert.equal(Number(after.score), 20); assert.equal(after.passed, false);
  assert.equal((await call("/api/management/reminders", { method: "POST", headers: auth(projectCookie), body: JSON.stringify({ assignmentIds: [locked.id] }) })).created, 1); assert.equal((await call("/api/management/reminders", { method: "POST", headers: auth(projectCookie), body: JSON.stringify({ assignmentIds: [locked.id] }) })).created, 0);
  console.log("DAY4_SMOKE_OPERATIONS");
  assert.equal((await call("/api/management/confirmations", { method: "POST", headers: auth(projectCookie), body: JSON.stringify({ assignmentIds: [pendingConfirm.id] }) })).confirmed, 1); assert.equal(await prisma.projectConfirmation.count({ where: { assignmentId: pendingConfirm.id } }), 1);
  const offline = await call("/api/management/offline-batches", { method: "POST", headers: auth(orgCookie), body: JSON.stringify({ name: "Day4 offline", type: "routine", content: "现场集中学习", date: new Date().toISOString(), hours: 2, instructor: "讲师", organizationId: org1.id, personIds: [people[0]!.id] }) }, 201); assert.equal(offline.count, 1); assert.equal(await prisma.trainingAssignment.count({ where: { batchId: offline.id, personId: people[0]!.id } }), 1);
  const change = await prisma.changeRequest.create({ data: { accountId: learner.id, personId: people[0]!.id, type: "profile_change", payload: { name: "Day4 updated", reason: "资料更正" } } }); await call(`/api/management/requests/${change.id}/approve`, { method: "POST", headers: auth(orgCookie), body: JSON.stringify({ note: "核验通过" }) }); assert.equal((await prisma.changeRequest.findUniqueOrThrow({ where: { id: change.id } })).reviewNote, "核验通过");
  console.log("DAY4_SMOKE_RECORDS");
  for (const type of ["ledger", "cards", "attendance", "scores", "annual"]) await call(`/api/reports/${type}`, { headers: auth(companyCookie) }); const csvResponse = await fetch(`${base}/api/reports/attendance?format=csv`, { headers: { cookie: companyCookie }, signal: AbortSignal.timeout(10_000) }); assert.equal(csvResponse.status, 200); assert.match(csvResponse.headers.get("content-type") ?? "", /text\/csv/);
  const wx = await call("/api/wechat/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code: "dev:day4-smoke" }) }); const bearer = { authorization: `Bearer ${wx.accessToken}`, "content-type": "application/json" }; await call("/api/management/overview", { headers: bearer }, 403); await call(`/api/me/records/${outside.id}`, { headers: bearer }, 404);
  assert.deepEqual((await call("/api/wechat/subscription-config", { headers: bearer })).templateIds, []); await call("/api/wechat/subscription-consent", { method: "POST", headers: bearer, body: JSON.stringify({ statuses: { "template-test": "reject" } }) });
  const bindingChange = await call("/api/me/change-requests", { method: "POST", headers: bearer, body: JSON.stringify({ type: "binding_change", reason: "更换微信绑定测试" }) }, 201); await call(`/api/management/requests/${bindingChange.id}/approve`, { method: "POST", headers: auth(orgCookie), body: JSON.stringify({ note: "确认换绑" }) }); await call("/api/auth/me", { headers: bearer }, 401);
  const changedPassword = randomBytes(24).toString("base64url"); const changed = await fetch(`${base}/api/auth/change-password`, { method: "POST", headers: auth(companyCookie), body: JSON.stringify({ currentPassword: password, newPassword: changedPassword }) }); assert.equal(changed.status, 204); await call("/api/auth/me", { headers: auth(companyCookie) }, 401); assert.ok(await login(company.username!, changedPassword));
  assert.ok(await prisma.auditLog.findFirst({ where: { action: "assignment.unlock", objectId: locked.id } })); console.log("DAY4_SMOKE_OK");
}
main().finally(() => prisma.$disconnect());
