import assert from "node:assert/strict";
import { reportStats, validateReportFields } from "../src/project-reporting-core.js";
import { canGovernMonthlyReporting, canSubmitMonthlyFacts, inheritedMonthlyDefaults, nextSubmissionStatus } from "../src/project-reporting-policy.js";

const fields = [{ fieldKey: "project_manager", label: "项目负责人", required: true, active: true, fieldType: "text" as const, options: [] }, { fieldKey: "custom_level", label: "风险等级", required: true, active: true, fieldType: "select" as const, options: ["低", "中", "高"] }];
assert.deepEqual(validateReportFields({ project_manager: "匿名负责人", custom_level: "中", safetyHazards: false }, fields), []);
assert.deepEqual(validateReportFields({ project_manager: "", custom_level: "未知", safetyHazards: true }, fields), ["项目负责人必填", "风险等级必须从配置选项中选择", "存在安全隐患时必须填写隐患详情"]);
const principal = (role: string, scopeType: string, scopeId: string | null, organizationType?: string) => ({ roles: [{ role, scopeType, scopeId, organizationType }] });
assert.equal(canSubmitMonthlyFacts(principal("company_admin", "company", null)), false);
assert.equal(canSubmitMonthlyFacts(principal("project_admin", "project", "project-a")), false);
assert.equal(canSubmitMonthlyFacts(principal("org_leader", "organization", "org-a", "business_entity")), false);
assert.equal(canSubmitMonthlyFacts(principal("org_admin", "organization", "org-a", "business_entity")), false);
assert.equal(canSubmitMonthlyFacts(principal("field_reporter", "organization", "org-a", "business_entity")), true);
assert.equal(canSubmitMonthlyFacts(principal("field_reporter", "organization", "org-a", "department")), false);
assert.equal(canGovernMonthlyReporting(principal("company_admin", "company", null)), true);
assert.equal(canGovernMonthlyReporting(principal("field_reporter", "organization", "org-a", "business_entity")), false);
assert.deepEqual(inheritedMonthlyDefaults({ overallProgress: "35%", onsiteCount: 8, onsiteVehicles: 2, equipmentModels: "钻机 2 台", monthlyConstructionStatus: "旧施工内容", safetyInspection: true, safetyHazards: true, safetyHazardDetail: "旧隐患" }), { overallProgress: "35%", onsiteCount: 8, onsiteVehicles: 2, equipmentModels: "钻机 2 台" });
assert.equal(nextSubmissionStatus("draft", "submit"), "submitted");
assert.equal(nextSubmissionStatus("rejected", "submit"), "submitted");
assert.equal(nextSubmissionStatus("submitted", "confirm"), "confirmed");
assert.equal(nextSubmissionStatus("submitted", "reject"), "rejected");
assert.equal(nextSubmissionStatus("confirmed", "lock"), "locked");
assert.throws(() => nextSubmissionStatus("draft", "confirm"), /状态不允许/);
assert.deepEqual(reportStats([{ id: "a" }, { id: "b" }, { id: "c" }], [{ reportingOrganizationId: "a", onsiteCount: 5, onsiteVehicles: 2, safetyHazards: true, safetyInspection: true }], [{ organizationId: "a", status: "submitted", reportType: "projects" }, { organizationId: "b", status: "confirmed", reportType: "no_projects" }]), { departmentTotal: 3, submittedDepartments: 2, noFieldDepartments: 1, missingDepartments: 1, projectCount: 1, onsitePeople: 5, onsiteVehicles: 2, hazardProjects: 1, inspectionRate: 100 });
console.log("PROJECT_REPORTING_POLICY_OK");
